[version]
path = "src/dqutils/release.py"

[build]
exclude = [
    "/.*",
    "Pipfile*",
]
[build.targets.wheel]
exclude = [
    "/tests",
]
ignore-vcs = true

[envs.types]
dependencies = [
    "mypy~=1.15"
]
[envs.types.scripts]
check = "mypy --strict {args:src/dqutils}"

[envs.hatch-static-analysis]
config-path = "ruff_defaults.toml"
dependencies = [
  "ruff~=0.11"
]

#[envs.hatch-static-analysis.scripts]

# hatch fmt -f --check src/dqutils
#format-check = "ruff format --check --diff {args:src/dqutils}"

# hatch fmt -f src/dqutils
#format-fix = "ruff format {args:src/dqutils}"

# hatch fmt -l --check src/dqutils
#lint-check = "ruff check {args:src/dqutils}"

# hatch fmt -l src/dqutils
#lint-fix = "ruff check --fix {args:src/dqutils}"

[[envs.hatch-test.matrix]]
python = ["3.13"]
