# pytest.ini
# See https://docs.pytest.org/en/latest/reference/reference.html#configuration-options
[pytest]
minversion = 8.3
pythonpath = src tests
testpaths = tests
addopts = --import-mode=importlib
