name: Test

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ['3.13', '3.14']
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Test
      run: |
        hatch test --python ${{ matrix.python-version }}
